### ISSUE TITLE
Warning "Invalid POM for com.sun.istack"

### ISSUE THREAD

**Issue by lca-afi** [eclipse-ee4j/jaxb-istack-commons#14]
We are currently migrating from Java 8 to OpenJDK 11 and during our Maven build now we get the following error:

"Invalid POM for com.sun.istack:istack-commons-runtime:jar:3.0.7, transitive dependencies (if any) will not be available, enable debug logging for more details$/"

Is there a quick solution to solve this?
If not, what could be done, that it is solved?

**Comment by lukasj** [comment]
works fine for me now
