### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-istack-commons#30]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
Release job passed: https://jenkins.eclipse.org/jaxb-impl/job/nexus-staging/33/console
PR to merge release info: https://github.com/eclipse-ee4j/jaxb-istack-commons/pull/31
