### ISSUE TITLE
Is maven plugin threadsafe?

### ISSUE THREAD

**Issue by thomasmey** [eclipse-ee4j/jaxb-istack-commons#60]
Hi,

is the maven plugin threadsafe and does the plugin just miss the @Threadsafe annotation?

When building with maven parallel builder (e.g. "mvn -T 1C install") I get this warning:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in jersey-core-common:
[WARNING] com.sun.istack:istack-commons-maven-plugin:3.0.8
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************

**Comment by lukasj** [comment]
fixed by #62
