### ISSUE TITLE
Updating from 3.0.12 -> 4.0.1 breaks ByteArrayDataSource

### ISSUE THREAD

**Issue by bencalegari** [eclipse-ee4j/jaxb-istack-commons#86]
In attempting to update to 4.0.1, we get a compilation error here:

https://github.com/codeforamerica/shiba/blob/2b4d0a3377b5097dba3f078fdf127ca94f42892e/src/main/java/org/codeforamerica/shiba/mnit/MnitEsbWebServiceClient.java#L107-L108

It appears the version of `jakarta.activation` no longer has a `DataSource` interface. In our project we don't specify a version: https://github.com/codeforamerica/shiba/blob/af3a156ff2e5633e63be7ea2ec07ef37273a994e/build.gradle#L106

Manually setting `jakarta.activation` to 2.0.1 (as it's set in your pom.xml) fixes that particular issue but a different class fails to compile within that library. Any suggestions?

**Comment by lukasj** [comment]
3 vs 4 signals major, possibly breaking change; with istack-commons 4+, one has to use activation 2+, older versions of activation won't work, see https://projects.eclipse.org/projects/ee4j.jaf/releases/2.0/plan for details

**Comment by lukasj** [comment]
also note that istack 3x supports "javax..." namespace (javax.activation), while 4x supports "jakarta..." namespace (jakarta.activation)

**Comment by bencalegari** [comment]
As I mentioned, upgrading to activation 2.0.1 didn't fix the problem. 

For anyone else who comes across this: To fix it I included the Apache Commons Email library as a dependency and used its `ByteArrayDataSource` instead of the one from `istack`: 

```groovy
implementation 'org.apache.commons:commons-email:1.5'
```

**Comment by lukasj** [comment]
the compiler fails to compile: `javax.activation.DataHandler(jakarta.activation.DataSource)`, javax.activation.DataHandler *requires* javax.activation.DataSource
