### ISSUE TITLE
groupId?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jaxb-istack-commons#9]
The groupId here is a very historic one: "com.sun.istack". Shouldn't it become something like "org.eclipse.ee4j.istack" or similar?

**Comment by m0mus** [comment]
This project is old, it explains having the old groupId. We are not planning to change it now.

It's a good suggestion to EE4J PMC to come out with some *recommended* groupId for older projects.

**Comment by keilw** [comment]
Maybe a stability badge similar to what we're using for JSR 385 and related projects could help?
https://github.com/unitsofmeasurement/seshat is "experimental"
https://github.com/unitsofmeasurement/uom-se is in "maintenance"

Some of those projects may also fall under the "dormant" or "mature/stable" categories we spoke about in the Spec Committee (not sure, how many of this week's calls you joined?)

**Comment by lukasj** [comment]
I don't think changing groupId for this really low-level component at this point makes sense. In the end, the effect would be that >5 consuming projects (jaxb, jaxws, policy, wsit and jersey at least) would need to change to adopt it. If there will be an official decision coming from PMC/spec committee to do it, then we can deal with it but till then, I'm closing this.
